export default [
  ['Array', 'Array', () => import(/* webpackChunkName: "docs/Array/Array" */ './docs/Array.md')],

  '属性',
  ['Array.length', 'length', () => import(/* webpackChunkName: "docs/Array/length" */ './docs/length.md')],
  ['Array.prototype', 'prototype', () => import(/* webpackChunkName: "docs/Array/prototype" */ './docs/prototype.md')],
  ['Array.prototype[@@unscopables] [es6]', 'unscopables', () => import(/* webpackChunkName: "docs/Array/unscopables" */ './docs/unscopables.md')],

  '方法',
  ['Array.from() [es6]', 'from', () => import(/* webpackChunkName: "docs/Array/from" */ './docs/from.md')],
  ['Array.isArray()', 'isArray', () => import(/* webpackChunkName: "docs/Array/isArray" */ './docs/isArray.md')],
  ['Array.observe() [已废弃]', null, null],
  ['Array.unobserve() [已废弃]', null, null],
  ['Array.of() [es6]', 'of', () => import(/* webpackChunkName: "docs/Array/of" */ './docs/of.md')],

  '实例方法',
  ['Array.prototype.concat()', 'concat', () => import(/* webpackChunkName: "docs/Array/concat" */ './docs/concat.md')],
  ['Array.prototype.copyWithin() [es6]', 'copyWithin', () => import(/* webpackChunkName: "docs/Array/copyWithin" */ './docs/copyWithin.md')],
  ['Array.prototype.entries() [es6]', 'entries', () => import(/* webpackChunkName: "docs/Array/entries" */ './docs/entries.md')],
  ['Array.prototype.every()', 'every', () => import(/* webpackChunkName: "docs/Array/every" */ './docs/every.md')],
  ['Array.prototype.fill() [es6]', 'fill', () => import(/* webpackChunkName: "docs/Array/fill" */ './docs/fill.md')],
  ['Array.prototype.filter()', 'filter', () => import(/* webpackChunkName: "docs/Array/filter" */ './docs/filter.md')],
  ['Array.prototype.find() [es6]', 'find', () => import(/* webpackChunkName: "docs/Array/find" */ './docs/find.md')],
  ['Array.prototype.findIndex() [es6]', 'findIndex', () => import(/* webpackChunkName: "docs/Array/findIndex" */ './docs/findIndex.md')],
  ['Array.prototype.forEach()', 'forEach', () => import(/* webpackChunkName: "docs/Array/forEach" */ './docs/forEach.md')],
  ['Array.prototype.includes() [es6]', 'includes', () => import(/* webpackChunkName: "docs/Array/includes" */ './docs/includes.md')],
  ['Array.prototype.indexOf()', 'indexOf', () => import(/* webpackChunkName: "docs/Array/indexOf" */ './docs/indexOf.md')],
  ['Array.prototype.join()', 'join', () => import(/* webpackChunkName: "docs/Array/join" */ './docs/join.md')],
  ['Array.prototype.keys() [es6]', 'keys', () => import(/* webpackChunkName: "docs/Array/keys" */ './docs/keys.md')],
  ['Array.prototype.lastIndexOf()', 'lastIndexOf', () => import(/* webpackChunkName: "docs/Array/lastIndexOf" */ './docs/lastIndexOf.md')],
  ['Array.prototype.map()', 'map', () => import(/* webpackChunkName: "docs/Array/map" */ './docs/map.md')],
  ['Array.prototype.pop()', 'pop', () => import(/* webpackChunkName: "docs/Array/pop" */ './docs/pop.md')],
  ['Array.prototype.push()', 'push', () => import(/* webpackChunkName: "docs/Array/push" */ './docs/push.md')],
  ['Array.prototype.reduce()', 'reduce', () => import(/* webpackChunkName: "docs/Array/reduce" */ './docs/reduce.md')],
  ['Array.prototype.reduceRight()', 'reduceRight', () => import(/* webpackChunkName: "docs/Array/reduceRight" */ './docs/reduceRight.md')],
  ['Array.prototype.reverse()', 'reverse', () => import(/* webpackChunkName: "docs/Array/reverse" */ './docs/reverse.md')],
  ['Array.prototype.shift()', 'shift', () => import(/* webpackChunkName: "docs/Array/shift" */ './docs/shift.md')],
  ['Array.prototype.slice()', 'slice', () => import(/* webpackChunkName: "docs/Array/slice" */ './docs/slice.md')],
  ['Array.prototype.some()', 'some', () => import(/* webpackChunkName: "docs/Array/some" */ './docs/some.md')],
  ['Array.prototype.sort()', 'sort', () => import(/* webpackChunkName: "docs/Array/sort" */ './docs/sort.md')],
  ['Array.prototype.splice()', 'splice', () => import(/* webpackChunkName: "docs/Array/splice" */ './docs/splice.md')],
  ['Array.prototype.toLocaleString() [草案]', 'toLocaleString', () => import(/* webpackChunkName: "docs/Array/toLocaleString" */ './docs/toLocaleString.md')],
  ['Array.prototype.toSource() [非标准]', null, null],
  ['Array.prototype.toString()', 'toString', () => import(/* webpackChunkName: "docs/Array/toString" */ './docs/toString.md')],
  ['Array.prototype.unshift()', 'unshift', () => import(/* webpackChunkName: "docs/Array/unshift" */ './docs/unshift.md')],
  ['Array.prototype.values() [es6]', 'values', () => import(/* webpackChunkName: "docs/Array/values" */ './docs/values.md')],
  ['Array.prototype[@@iterator]()  [es6]', 'iterator', () => import(/* webpackChunkName: "docs/Array/iterator" */ './docs/iterator.md')],
  ['get Array[@@species] [es6]', null, null]
];
