export default [
  '搬运自阮一峰ES6教程',
  ['ECMAScript 6简介', 'intro', () => import(/* webpackChunkName: "docs/es6/intro" */ './docs/intro.md')],
  ['let 和 const 命令', 'let', () => import(/* webpackChunkName: "docs/es6/let" */ './docs/let.md')],
  ['变量的解构赋值', 'destructuring', () => import(/* webpackChunkName: "docs/es6/destructuring" */ './docs/destructuring.md')],
  ['字符串的扩展', 'string', () => import(/* webpackChunkName: "docs/es6/string" */ './docs/string.md')],
  ['正则的扩展', 'regex', () => import(/* webpackChunkName: "docs/es6/regex" */ './docs/regex.md')],
  ['数值的扩展', 'number', () => import(/* webpackChunkName: "docs/es6/number" */ './docs/number.md')],
  ['函数的扩展', 'function', () => import(/* webpackChunkName: "docs/es6/function" */ './docs/function.md')],
  ['数组的扩展', 'array', () => import(/* webpackChunkName: "docs/es6/array" */ './docs/array.md')],
  ['对象的扩展', 'object', () => import(/* webpackChunkName: "docs/es6/object" */ './docs/object.md')],
  ['Symbol', 'symbol', () => import(/* webpackChunkName: "docs/es6/symbol" */ './docs/symbol.md')],
  ['Set 和 Map 数据结构', 'set-map', () => import(/* webpackChunkName: "docs/es6/set-map" */ './docs/set-map.md')],
  ['Proxy', 'proxy', () => import(/* webpackChunkName: "docs/es6/proxy" */ './docs/proxy.md')],
  ['Reflect', 'reflect', () => import(/* webpackChunkName: "docs/es6/reflect" */ './docs/reflect.md')],
  ['Promise 对象', 'promise', () => import(/* webpackChunkName: "docs/es6/promise" */ './docs/promise.md')],
  ['Iterator 和 for...of 循环', 'iterator', () => import(/* webpackChunkName: "docs/es6/iterator" */ './docs/iterator.md')],
  ['Generator 函数的语法', 'generator', () => import(/* webpackChunkName: "docs/es6/generator" */ './docs/generator.md')],
  ['Generator 函数的异步应用', 'generator-async', () => import(/* webpackChunkName: "docs/es6/generator-async" */ './docs/generator-async.md')],
  ['async 函数', 'async', () => import(/* webpackChunkName: "docs/es6/async" */ './docs/async.md')],
  ['Class 的基本语法', 'class', () => import(/* webpackChunkName: "docs/es6/class" */ './docs/class.md')],
  ['Class 的继承', 'class-extends', () => import(/* webpackChunkName: "docs/es6/class-extends" */ './docs/class-extends.md')],
  ['Decorator', 'decorator', () => import(/* webpackChunkName: "docs/es6/decorator" */ './docs/decorator.md')],
  ['Module 的语法', 'module', () => import(/* webpackChunkName: "docs/es6/module" */ './docs/module.md')],
  ['Module 的加载实现', 'module-loader', () => import(/* webpackChunkName: "docs/es6/module-loader" */ './docs/module-loader.md')],
  ['编程风格', 'style', () => import(/* webpackChunkName: "docs/es6/style" */ './docs/style.md')],
  ['读懂规格', 'spec', () => import(/* webpackChunkName: "docs/es6/spec" */ './docs/spec.md')],
  ['ArrayBuffer', 'arraybuffer', () => import(/* webpackChunkName: "docs/es6/arraybuffer" */ './docs/arraybuffer.md')],
  ['参考链接', 'reference', () => import(/* webpackChunkName: "docs/es6/reference" */ './docs/reference.md')]
];
