export default [
  ['Math', 'Math', () => import(/* webpackChunkName: "docs/Math/Math" */ './docs/Math.md')],

  '属性',
  ['Math.E', 'E', () => import(/* webpackChunkName: "docs/Math/E" */ './docs/E.md')],
  ['Math.LN2', 'LN2', () => import(/* webpackChunkName: "docs/Math/LN2" */ './docs/LN2.md')],
  ['Math.LN10', 'LN10', () => import(/* webpackChunkName: "docs/Math/LN10" */ './docs/LN10.md')],
  ['Math.LOG2E', 'LOG2E', () => import(/* webpackChunkName: "docs/Math/LOG2E" */ './docs/LOG2E.md')],
  ['Math.LOG10E', 'LOG10E', () => import(/* webpackChunkName: "docs/Math/LOG10E" */ './docs/LOG10E.md')],
  ['Math.PI', 'PI', () => import(/* webpackChunkName: "docs/Math/PI" */ './docs/PI.md')],
  ['Math.SQRT1_2', 'SQRT1_2', () => import(/* webpackChunkName: "docs/Math/SQRT1_2" */ './docs/SQRT1_2.md')],
  ['Math.SQRT2', 'SQRT2', () => import(/* webpackChunkName: "docs/Math/SQRT2" */ './docs/SQRT2.md')],

  '方法',
  ['Math.abs(x)', 'abs', () => import(/* webpackChunkName: "docs/Math/abs" */ './docs/abs.md')],
  ['Math.acos(x)', 'acos', () => import(/* webpackChunkName: "docs/Math/acos" */ './docs/acos.md')],
  ['Math.acosh(x) [es6]', 'acosh', () => import(/* webpackChunkName: "docs/Math/acosh" */ './docs/acosh.md')],
  ['Math.asin(x)', 'asin', () => import(/* webpackChunkName: "docs/Math/asin" */ './docs/asin.md')],
  ['Math.asinh(x) [es6]', 'asinh', () => import(/* webpackChunkName: "docs/Math/asinh" */ './docs/asinh.md')],
  ['Math.atan(x)', 'atan', () => import(/* webpackChunkName: "docs/Math/atan" */ './docs/atan.md')],
  ['Math.atanh(x) [es6]', 'atanh', () => import(/* webpackChunkName: "docs/Math/atanh" */ './docs/atanh.md')],
  ['Math.atan2(x, y)', 'atan2', () => import(/* webpackChunkName: "docs/Math/atan2" */ './docs/atan2.md')],
  ['Math.cbrt(x) [es6]', 'cbrt', () => import(/* webpackChunkName: "docs/Math/cbrt" */ './docs/cbrt.md')],
  ['Math.ceil(x)', 'ceil', () => import(/* webpackChunkName: "docs/Math/ceil" */ './docs/ceil.md')],
  ['Math.clz32(x) [es6]', 'clz32', () => import(/* webpackChunkName: "docs/Math/clz32" */ './docs/clz32.md')],
  ['Math.cos(x)', 'cos', () => import(/* webpackChunkName: "docs/Math/cos" */ './docs/cos.md')],
  ['Math.cosh(x) [es6]', 'cosh', () => import(/* webpackChunkName: "docs/Math/cosh" */ './docs/cosh.md')],
  ['Math.exp(x)', 'exp', () => import(/* webpackChunkName: "docs/Math/exp" */ './docs/exp.md')],
  ['Math.expm1(x) [es6]', 'expm1', () => import(/* webpackChunkName: "docs/Math/expm1" */ './docs/expm1.md')],
  ['Math.floor(x)', 'floor', () => import(/* webpackChunkName: "docs/Math/floor" */ './docs/floor.md')],
  ['Math.fround(x) [es6]', 'fround', () => import(/* webpackChunkName: "docs/Math/fround" */ './docs/fround.md')],
  ['Math.hypot() [es6]', 'hypot', () => import(/* webpackChunkName: "docs/Math/hypot" */ './docs/hypot.md')],
  ['Math.imul(x) [es6]', 'imul', () => import(/* webpackChunkName: "docs/Math/imul" */ './docs/imul.md')],
  ['Math.log(x)', 'log', () => import(/* webpackChunkName: "docs/Math/log" */ './docs/log.md')],
  ['Math.log1p(x) [es6]', 'log1p', () => import(/* webpackChunkName: "docs/Math/log1p" */ './docs/log1p.md')],
  ['Math.log10(x) [es6]', 'log10', () => import(/* webpackChunkName: "docs/Math/log10" */ './docs/log10.md')],
  ['Math.log2(x) [es6]', 'log2', () => import(/* webpackChunkName: "docs/Math/log2" */ './docs/log2.md')],
  ['Math.max()', 'max', () => import(/* webpackChunkName: "docs/Math/max" */ './docs/max.md')],
  ['Math.min()', 'min', () => import(/* webpackChunkName: "docs/Math/min" */ './docs/min.md')],
  ['Math.pow(x,y)', 'pow', () => import(/* webpackChunkName: "docs/Math/pow" */ './docs/pow.md')],
  ['Math.random()', 'random', () => import(/* webpackChunkName: "docs/Math/random" */ './docs/random.md')],
  ['Math.round(x)', 'round', () => import(/* webpackChunkName: "docs/Math/round" */ './docs/round.md')],
  ['Math.sign(x) [es6]', 'sign', () => import(/* webpackChunkName: "docs/Math/sign" */ './docs/sign.md')],
  ['Math.sin(x)', 'sin', () => import(/* webpackChunkName: "docs/Math/sin" */ './docs/sin.md')],
  ['Math.sinh(x) [es6]', 'sinh', () => import(/* webpackChunkName: "docs/Math/sinh" */ './docs/sinh.md')],
  ['Math.sqrt(x)', 'sqrt', () => import(/* webpackChunkName: "docs/Math/sqrt" */ './docs/sqrt.md')],
  ['Math.tan(x)', 'tan', () => import(/* webpackChunkName: "docs/Math/tan" */ './docs/tan.md')],
  ['Math.tanh(x) [es6]', 'tanh', () => import(/* webpackChunkName: "docs/Math/tanh" */ './docs/tanh.md')],
  ['Math.toSource()', null, null],
  ['Math.trunc(x) [es6]', 'trunc', () => import(/* webpackChunkName: "docs/Math/trunc" */ './docs/trunc.md')]
];
