export default [
  ['String', 'String', () => import(/* webpackChunkName: "docs/String/String" */ './docs/String.md')],

  '属性',
  ['String.prototype', 'prototype', () => import(/* webpackChunkName: "docs/String/prototype" */ './docs/prototype.md')],

  '方法',
  ['String.fromCharCode()', 'fromCharCode', () => import(/* webpackChunkName: "docs/String/fromCharCode" */ './docs/fromCharCode.md')],
  ['String.fromCodePoint() [es6]', 'fromCodePoint', () => import(/* webpackChunkName: "docs/String/fromCodePoint" */ './docs/fromCodePoint.md')],
  ['String.raw() [es6]', 'raw', () => import(/* webpackChunkName: "docs/String/raw" */ './docs/raw.md')],

  '实例属性',
  ['String.prototype.constructor', 'constructor', () => import(/* webpackChunkName: "docs/String/constructor" */ './docs/constructor.md')],
  ['String.prototype.length', 'length', () => import(/* webpackChunkName: "docs/String/length" */ './docs/length.md')],

  '实例方法',
  ['charAt()', 'charAt', () => import(/* webpackChunkName: "docs/String/charAt" */ './docs/charAt.md')],
  ['charCodeAt()', 'charCodeAt', () => import(/* webpackChunkName: "docs/String/charCodeAt" */ './docs/charCodeAt.md')],
  ['codePointAt() [es6]', 'codePointAt', () => import(/* webpackChunkName: "docs/String/codePointAt" */ './docs/codePointAt.md')],
  ['concat()', 'concat', () => import(/* webpackChunkName: "docs/String/concat" */ './docs/concat.md')],
  ['includes() [es6]', 'includes', () => import(/* webpackChunkName: "docs/String/includes" */ './docs/includes.md')],
  ['endsWith() [es6]', 'endsWith', () => import(/* webpackChunkName: "docs/String/endsWith" */ './docs/endsWith.md')],
  ['indexOf()', 'indexOf', () => import(/* webpackChunkName: "docs/String/indexOf" */ './docs/indexOf.md')],
  ['lastIndexOf()', 'lastIndexOf', () => import(/* webpackChunkName: "docs/String/lastIndexOf" */ './docs/lastIndexOf.md')],
  ['localeCompare()', 'localeCompare', () => import(/* webpackChunkName: "docs/String/localeCompare" */ './docs/localeCompare.md')],
  ['match()', 'match', () => import(/* webpackChunkName: "docs/String/match" */ './docs/match.md')],
  ['normalize() [es6]', 'normalize', () => import(/* webpackChunkName: "docs/String/normalize" */ './docs/normalize.md')],
  ['repeat() [es6]', 'repeat', () => import(/* webpackChunkName: "docs/String/repeat" */ './docs/repeat.md')],
  ['replace()', 'replace', () => import(/* webpackChunkName: "docs/String/replace" */ './docs/replace.md')],
  ['search()', 'search', () => import(/* webpackChunkName: "docs/String/search" */ './docs/search.md')],
  ['slice()', 'slice', () => import(/* webpackChunkName: "docs/String/slice" */ './docs/slice.md')],
  ['split()', 'split', () => import(/* webpackChunkName: "docs/String/split" */ './docs/split.md')],
  ['startsWith() [es6]', 'startsWith', () => import(/* webpackChunkName: "docs/String/startsWith" */ './docs/startsWith.md')],
  ['substr()', 'substr', () => import(/* webpackChunkName: "docs/String/substr" */ './docs/substr.md')],
  ['substring()', 'substring', () => import(/* webpackChunkName: "docs/String/substring" */ './docs/substring.md')],
  ['toLocaleLowerCase()', 'toLocaleLowerCase', () => import(/* webpackChunkName: "docs/String/toLocaleLowerCase" */ './docs/toLocaleLowerCase.md')],
  ['toLocaleUpperCase()', 'toLocaleUpperCase', () => import(/* webpackChunkName: "docs/String/toLocaleUpperCase" */ './docs/toLocaleUpperCase.md')],
  ['toLowerCase()', 'toLowerCase', () => import(/* webpackChunkName: "docs/String/toLowerCase" */ './docs/toLowerCase.md')],
  ['toString()', 'toString', () => import(/* webpackChunkName: "docs/String/toString" */ './docs/toString.md')],
  ['toUpperCase()', 'toUpperCase', () => import(/* webpackChunkName: "docs/String/toUpperCase" */ './docs/toUpperCase.md')],
  ['trim()', 'trim', () => import(/* webpackChunkName: "docs/String/trim" */ './docs/trim.md')],
  ['valueOf()', 'valueOf', () => import(/* webpackChunkName: "docs/String/valueOf" */ './docs/valueOf.md')],
  ['toSource() [非标准]', 'toSource', () => import(/* webpackChunkName: "docs/String/toSource" */ './docs/toSource.md')],
  ['quote() [非标准]', 'quote', () => import(/* webpackChunkName: "docs/String/quote" */ './docs/quote.md')],
  ['trimLeft() [非标准]', 'trimLeft', () => import(/* webpackChunkName: "docs/String/trimLeft" */ './docs/trimLeft.md')],
  ['trimRight() [非标准]', 'trimRight', () => import(/* webpackChunkName: "docs/String/trimRight" */ './docs/trimRight.md')]
];
