export default [
  ['Object', 'Object', () => import(/* webpackChunkName: "docs/Object/Object" */ './docs/Object.md')],

  '属性',
  ['Object.length', 'length', () => import(/* webpackChunkName: "docs/Object/length" */ './docs/length.md')],

  '方法',
  ['Object.assign()', 'assign', () => import(/* webpackChunkName: "docs/Object/assign" */ './docs/assign.md')],
  ['Object.create()', 'create', () => import(/* webpackChunkName: "docs/Object/create" */ './docs/create.md')],
  ['Object.defineProperty()', 'defineProperty', () => import(/* webpackChunkName: "docs/Object/defineProperty" */ './docs/defineProperty.md')],
  ['Object.defineProperties()', 'defineProperties', () => import(/* webpackChunkName: "docs/Object/defineProperties" */ './docs/defineProperties.md')],
  ['Object.getOwnPropertyDescriptor()', 'getOwnPropertyDescriptor', () => import(/* webpackChunkName: "docs/Object/getOwnPropertyDescriptor" */ './docs/getOwnPropertyDescriptor.md')],
  ['Object.getOwnPropertyNames()', 'getOwnPropertyNames', () => import(/* webpackChunkName: "docs/Object/getOwnPropertyNames" */ './docs/getOwnPropertyNames.md')],
  ['Object.getOwnPropertySymbols()', 'getOwnPropertySymbols', () => import(/* webpackChunkName: "docs/Object/getOwnPropertySymbols" */ './docs/getOwnPropertySymbols.md')],
  ['Object.getPrototypeOf()', 'getPrototypeOf', () => import(/* webpackChunkName: "docs/Object/getPrototypeOf" */ './docs/getPrototypeOf.md')],
  ['Object.setPrototypeOf()', 'setPrototypeOf', () => import(/* webpackChunkName: "docs/Object/setPrototypeOf" */ './docs/setPrototypeOf.md')],
  ['Object.is()', 'is', () => import(/* webpackChunkName: "docs/Object/is" */ './docs/is.md')],
  ['Object.isExtensible()', 'isExtensible', () => import(/* webpackChunkName: "docs/Object/isExtensible" */ './docs/isExtensible.md')],
  ['Object.freeze()', 'freeze', () => import(/* webpackChunkName: "docs/Object/freeze" */ './docs/freeze.md')],
  ['Object.isFrozen()', 'isFrozen', () => import(/* webpackChunkName: "docs/Object/isFrozen" */ './docs/isFrozen.md')],
  ['Object.seal()', 'seal', () => import(/* webpackChunkName: "docs/Object/seal" */ './docs/seal.md')],
  ['Object.isSealed()', 'isSealed', () => import(/* webpackChunkName: "docs/Object/isSealed" */ './docs/isSealed.md')],
  ['Object.keys()', 'keys', () => import(/* webpackChunkName: "docs/Object/keys" */ './docs/keys.md')],
  ['Object.preventExtensions()', 'preventExtensions', () => import(/* webpackChunkName: "docs/Object/preventExtensions" */ './docs/preventExtensions.md')],
  ['Object.entries() [草案]', '', ''],
  ['Object.values() [草案]', '', ''],

  '实例属性',
  ['Object.prototype.constructor', 'constructor', () => import(/* webpackChunkName: "docs/Object/constructor" */ './docs/constructor.md')],
  ['Object.prototype.__proto__ [非标准]', '', ''],
  ['Object.prototype.__noSuchMethod__ [非标准]', '', ''],
  ['Object.prototype.__count__ [已废弃]', '', ''],
  ['Object.prototype.__parent__ [已废弃]', '', ''],

  '实例方法',
  ['Object.prototype.hasOwnProperty()', 'hasOwnProperty', () => import(/* webpackChunkName: "docs/Object/hasOwnProperty" */ './docs/hasOwnProperty.md')],
  ['Object.prototype.isPrototypeOf()', 'isPrototypeOf', () => import(/* webpackChunkName: "docs/Object/isPrototypeOf" */ './docs/isPrototypeOf.md')],
  ['Object.prototype.propertyIsEnumerable()', 'propertyIsEnumerable', () => import(/* webpackChunkName: "docs/Object/propertyIsEnumerable" */ './docs/propertyIsEnumerable.md')],
  ['Object.prototype.toLocaleString()', 'toLocaleString', () => import(/* webpackChunkName: "docs/Object/toLocaleString" */ './docs/toLocaleString.md')],
  ['Object.prototype.toString()', 'toString', () => import(/* webpackChunkName: "docs/Object/toString" */ './docs/toString.md')],
  ['Object.prototype.valueOf()', 'valueOf', () => import(/* webpackChunkName: "docs/Object/valueOf" */ './docs/valueOf.md')],
  ['Object.prototype.toSource() [非标准]', '', ''],
  ['Object.prototype.unwatch() [非标准]', '', ''],
  ['Object.prototype.watch() [非标准]', '', ''],
  ['Object.prototype.__defineGetter__() [已废弃]', '', ''],
  ['Object.prototype.__defineSetter__() [已废弃]', '', ''],
  ['Object.prototype.__lookupGetter__() [已废弃]', '', ''],
  ['Object.prototype.__lookupSetter__() [已废弃]', '', ''],
  ['Object.prototype.eval() [已废弃]', '', '']
];
